### ISSUE TITLE
simple example with error from rust documentation, how to run?

### ISSUE THREAD

**Issue by andreykl** [xldenis/creusot#720]
Hello again!

While trying to run this code (from https://doc.rust-lang.org/std/error/trait.Error.html) getting erros like below
```bash
$ cargo creusot -- --features=contracts
   Compiling pearlite-syn v0.2.0 (../creusot/creusot/pearlite-syn)
error[E0599]: no variant or associated item named `AddEq` found for enum `BinOp` in the current scope
   --> ../creusot/creusot/pearlite-syn/src/term.rs:648:24
    |
648 |                 BinOp::AddEq(_)
    |                        ^^^^^ variant or associated item not found in `BinOp`
...
```

I wonder if I didnt import something correctly ?

------------------------------
code 
------------------------------
`$ cat src/main.rs`
```rust
use creusot_contracts::*;
use std::error::Error;
use std::fmt;

#[derive(Debug)]
struct SuperError {
    source: SuperErrorSideKick,
}

impl fmt::Display for SuperError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "SuperError is here!")
    }
}

impl Error for SuperError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(&self.source)
    }
}

#[derive(Debug)]
struct SuperErrorSideKick;

impl fmt::Display for SuperErrorSideKick {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "SuperErrorSideKick is here!")
    }
}

impl Error for SuperErrorSideKick {}

fn get_super_error() -> Result<(), SuperError> {
    Err(SuperError { source: SuperErrorSideKick })
}

fn main() {
    match get_super_error() {
        Err(e) => {
            println!("Error: {e}");
            println!("Caused by: {}", e.source().unwrap());
        }
        _ => println!("No error"),
    }
}
```

`$ cat Cargo.toml`
```toml

[package]
name = "test_error"
version = "0.1.0"
edition = "2021"

[dependencies]
#clap = "2.33.3"
creusot-contracts = { path = "../creusot/creusot-contracts"  }

[features]
contracts = ["creusot-contracts/contracts"]

```
`$ cat rust-toolchain`
```toml
[toolchain]
channel = "nightly-2023-01-15"
components = [ "rustfmt", "rustc-dev", "llvm-tools-preview" ]
```
